server:
  port: 8080
  servlet:
    context-path: /winter
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false

logging:
  level:
    shupeyko.services: DEBUG

integrations:
  cart-service:
    url: http://localhost:8190/winter-carts
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000