server:
  port: 5555

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:3000/realms/master
          jwk-set-uri: http://localhost:3000/realms/master/protocol/openid-connect/certs
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8080
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market
            - JwtAuthFilter
        - id: cart-service
          uri: http://localhost:8190
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-carts
            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8187
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-auth
            - JwtAuthFilter

jwt:
  secret: Ymj5peSjMsSe77uNCyPHqPcO5tOI5bQIZciJBATt6ZXy

#logging:
#  level:
#    reactor:
#      netty: TRACE
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE
